name: habitai
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_crashlytics: ^3.3.5
  flutter_colorpicker: ^1.1.0
  firebase_analytics: ^10.4.5
  firebase_messaging: ^14.6.7
  cloud_firestore: ^4.8.5
  google_sign_in: ^6.1.4
  flutter_signin_button: ^2.0.0
  flutter_dotenv: ^6.0.0
  http: ^1.6.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  purchases_flutter: ^9.9.9
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bgimages/
    - assets/icons/
    - assets/.env.dev
    - assets/.env.staging
    - assets/.env.prod
